NAME = ft_display_file
CC = gcc
CFLAGS = -Wall -Wextra -Werror 
OBJ = ft_display_file.o

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) -o $(NAME) $(OBJ)

clean:
	/bin/rm -f $(OBJ)

fclean: clean
	/bin/rm -f $(NAME)
